import { Article } from "./types";

export const sampleArticles: Article[] = [
  // Articles Included Column (default for all new articles)
  {
    id: "1",
    title: "EU AI Act: What Financial Institutions Need to Know",
    description: "A comprehensive guide to the European Union's Artificial Intelligence Act and its implications for banks, insurers, and investment firms.",
    link: "https://example.com/eu-ai-act-finance",
    sourceType: "cron",
    sourceTimestamp: new Date("2026-01-27T09:30:00"),
    additionalSources: ["playground"],
    similarSources: [
      { title: "EU AI Act Official Text", link: "https://eur-lex.europa.eu/ai-act" },
      { title: "AI Compliance Framework Guide", link: "https://example.com/ai-compliance" },
    ],
    lastModification: null,
    columnId: "included",
  },
  {
    id: "2",
    title: "DORA Compliance Checklist for 2026",
    description: "Digital Operational Resilience Act requirements and timeline for financial entities operating in the EU.",
    link: "https://example.com/dora-checklist-2026",
    sourceType: "playground",
    sourceTimestamp: new Date("2026-01-27T11:00:00"),
    additionalSources: [],
    similarSources: [
      { title: "DORA Implementation Timeline", link: "https://example.com/dora-timeline" },
    ],
    lastModification: null,
    columnId: "included",
  },
  {
    id: "3",
    title: "Basel IV Implementation: RegTech Solutions",
    description: "How regulatory technology can help banks meet Basel IV capital requirements more efficiently.",
    link: "https://example.com/basel-iv-regtech",
    sourceType: "cron",
    sourceTimestamp: new Date("2026-01-27T06:00:00"),
    additionalSources: [],
    similarSources: [],
    lastModification: null,
    columnId: "included",
  },
  {
    id: "4",
    title: "KYC Automation: Best Practices for 2026",
    description: "Latest trends in Know Your Customer automation using AI and machine learning.",
    link: "https://example.com/kyc-automation-2026",
    sourceType: "manual",
    sourceTimestamp: new Date("2026-01-23T15:45:00"),
    additionalSources: [],
    similarSources: [
      { title: "FATF KYC Guidelines", link: "https://fatf-gafi.org/kyc" },
      { title: "Digital Identity Verification Standards", link: "https://example.com/identity-standards" },
      { title: "ML in KYC Whitepaper", link: "https://example.com/ml-kyc-paper" },
    ],
    lastModification: {
      type: "created",
      by: "Sarah Johnson",
      timestamp: new Date("2026-01-23T15:45:00"),
    },
    columnId: "included",
  },
  {
    id: "5",
    title: "MiCA Regulation: Crypto Asset Service Providers Guide",
    description: "Markets in Crypto-Assets regulation compliance requirements for CASPs operating in the European Union.",
    link: "https://example.com/mica-casp-guide",
    sourceType: "cron",
    sourceTimestamp: new Date("2026-01-20T08:00:00"),
    additionalSources: ["manual"],
    similarSources: [
      { title: "MiCA Official Regulation", link: "https://eur-lex.europa.eu/mica" },
      { title: "ESMA MiCA Guidelines", link: "https://esma.europa.eu/mica-guidelines" },
    ],
    lastModification: null,
    columnId: "included",
  },
  {
    id: "6",
    title: "AML 6th Directive: Technology Solutions",
    description: "Anti-Money Laundering technology solutions to meet the 6th AML Directive requirements.",
    link: "https://example.com/aml6-tech-solutions",
    sourceType: "playground",
    sourceTimestamp: new Date("2026-01-18T13:20:00"),
    additionalSources: [],
    similarSources: [
      { title: "6AMLD Key Changes Summary", link: "https://example.com/6amld-changes" },
    ],
    lastModification: null,
    columnId: "included",
  },
  {
    id: "7",
    title: "RegTech Market Report Q1 2026",
    description: "Quarterly analysis of the regulatory technology market, including funding trends and emerging players.",
    link: "https://example.com/regtech-market-q1-2026",
    sourceType: "manual",
    sourceTimestamp: new Date("2026-01-15T16:00:00"),
    additionalSources: ["cron", "playground"],
    similarSources: [
      { title: "RegTech 100 List 2026", link: "https://example.com/regtech-100" },
      { title: "FinTech Global Report", link: "https://fintechglobal.com/report-2026" },
    ],
    lastModification: {
      type: "created",
      by: "David Park",
      timestamp: new Date("2026-01-15T16:00:00"),
    },
    columnId: "included",
  },

  // Articles Excluded Column (explicitly excluded by users)
  {
    id: "8",
    title: "Generic Fintech Trends Article",
    description: "A broad overview of fintech trends without specific regulatory focus.",
    link: "https://example.com/fintech-trends-generic",
    sourceType: "cron",
    sourceTimestamp: new Date("2026-01-22T06:00:00"),
    additionalSources: [],
    similarSources: [],
    lastModification: {
      type: "dragged",
      by: "Lisa Thompson",
      timestamp: new Date("2026-01-23T11:00:00"),
      details: {
        fromColumn: "included",
        toColumn: "excluded",
      },
    },
    columnId: "excluded",
  },
  {
    id: "9",
    title: "Cryptocurrency Price Predictions 2026",
    description: "Speculative article about crypto prices - not relevant to regulatory compliance.",
    link: "https://example.com/crypto-predictions",
    sourceType: "playground",
    sourceTimestamp: new Date("2026-01-21T09:45:00"),
    additionalSources: [],
    similarSources: [],
    lastModification: {
      type: "dragged",
      by: "Michael Chen",
      timestamp: new Date("2026-01-21T16:30:00"),
      details: {
        fromColumn: "included",
        toColumn: "excluded",
      },
    },
    columnId: "excluded",
  },
  {
    id: "10",
    title: "Bank Marketing Strategies",
    description: "Article about marketing and customer acquisition - not compliance related.",
    link: "https://example.com/bank-marketing",
    sourceType: "cron",
    sourceTimestamp: new Date("2026-01-19T06:00:00"),
    additionalSources: [],
    similarSources: [],
    lastModification: {
      type: "dragged",
      by: "Emma Wilson",
      timestamp: new Date("2026-01-19T14:20:00"),
      details: {
        fromColumn: "included",
        toColumn: "excluded",
      },
    },
    columnId: "excluded",
  },
];
